### ISSUE TITLE
W3M1 - Not displaying some images

### ISSUE THREAD

**Issue by cclarkson** [anopheles-genomic-surveillance/anopheles-genomic-surveillance.github.io#75]
e.g. [https://anopheles-genomic-surveillance.github.io/workshop-3/module-1-plotly.html](https://anopheles-genomic-surveillance.github.io/workshop-3/module-1-plotly.html)

**Comment by alimanfoo** [comment]
Still looks relevant, e.g.:

![image](https://user-images.githubusercontent.com/703554/225412718-4076d0fd-3edd-44fc-8549-a4393697b7ff.png)

Think this just requires changing from markdown image to html `<img>` tag, because markdown image tags don't seem to get recognised or rendered properly by jupyterbook.
